### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by Naimul007A** [asifakonjee/ibus-hyprland#1]
Can you help me to setup  ibus in hyprland.I don't understand your repo :)

**Comment by asifakonjee** [comment]
@Naimul007A... Please use fcitx5 and openbangla keyboard's develop version. I have another repo and script which will install all by a single command.

**Comment by asifakonjee** [comment]
@Naimul007A... You will find the repo named openbangla-script. Here is the install  command

```
bash -c "$(wget -q https://raw.githubusercontent.com/asifakonjee/openbangla-script/master/installer.sh -O -)"
```

**Comment by Naimul007A** [comment]
> @Naimul007A... You will find the repo named openbangla-script. Here is the install command
> 
> ```
> bash -c "$(wget -q https://raw.githubusercontent.com/asifakonjee/openbangla-script/master/installer.sh -O -)"
> ```

Thank you so much.it's working now.Again thanks
